// Q1.GIVEN AN ARRAY OF INTEGERS, EVERY ELEMENT APPEARS TWICE EXCEPT FOR ONE. FIND THAT ONE.

// Q2.IF YOU WERE DESIGNING A WEB CRAWLER, HOW WOULD YOU AVOID GETTING INTO INFINITE LOOPS?

// Q3.Algorithm to convert Roman Numerals to Integer Number?